---
version: 0.3.2
files:
  README.md:
  - straw-ios.js v%.%.%
  - doc/v%.%.%
  package.json: ! '"version": "%.%.%"'
  bower.json: ! '"version": "%.%.%"'
  straw-ios.js: ! 'version: ''v%.%.%'''
  .jsduck.release.json: ! '"doc/v%.%.%"'
